
[unreleased]
added = [
    "Diagnostic for license field in Cargo.toml",
    "Diagnostic for description field in Cargo.toml",
    "Diagnostic for documentation field in Cargo.toml",
    "Diagnostic for repository field in Cargo.toml",
]
